New job-template, job-group for horizon to test the rebase fix
job-template - "{name}-jiocloud-rebase-fix-testing"
* A rebase would have rewritten the branch history so...
removed the code to that does 'git pull' and...
if 'jiocloud_master' branch existed, delete it and fetch the latest and...
do a fresh checkout for every run of the job.
* Push the rebased code irrespective of whether tox tests pass.
This is temporary, until we figure out a way to resolve
the tox tests issue with our jio-master

Other than the above change, the rest is just a copy of the existing template
"{name}-jiocloud".

diff --git a/jobs.yaml b/jobs.yaml
--- a/jobs.yaml
+++ b/jobs.yaml
@@ -141,6 +141,122 @@
       - ssh-agent:
           credentials-id: 46c0cb26-2b11-443c-b556-0f7631f02410
 
+- job-template:
+    name: "{name}-jiocloud-rebase-fix-testing"
+    project-style: freestyle
+    parameters:
+      - string:
+          name: branch
+          default: unknown
+          description: "The branch that triggered the upstream build (if any)"
+    node: cloud
+    logrotate:
+      daysToKeep: 10
+      numToKeep: 20
+      artifactDaysToKeep: 7
+      artifactNumToKeep: 15
+
+    scm:
+      - git:
+          url: git@github.com:JioCloud/{name}.git
+          name: jiocloud
+          branches:
+            - jiocloud/devmaster
+          credentials-id: 46c0cb26-2b11-443c-b556-0f7631f02410
+
+    triggers:
+      - pollscm: "H/15 * * * *"
+
+    builders:
+      - shell: |
+          #!/bin/bash -x
+          # Make sure we have all the relevant remotes
+          if ! git remote | grep ^origin$
+          then
+              git remote add origin git@github.com:{organization}/{name}.git
+          fi
+          if ! git remote | grep ^jiocloud$
+          then
+              git remote add jiocloud git@github.com:JioCloud/{name}.git
+          fi
+          if [ "${{branch}}" = "origin/{srcbranch}" ]
+          then
+            if git branch | grep jiocloud_master
+            then
+                # a rebase would have rewritten the branch history
+                # so delete the existing jiocloud_master and do a fresh checkout
+                if [ "`git rev-parse --abbrev-ref HEAD`" == "jiocloud_master" ]
+                then
+                    # current branch can't be deleted
+                    # switch to master to delete the current branch
+                    git checkout master
+                fi
+                git branch -D jiocloud_master
+                # fetch the latest
+                git fetch jiocloud master
+            fi
+            # First make sure we have a local branch to work with
+            git checkout -b jiocloud_master jiocloud/master
+
+            # Make sure we have the relevant commit
+            git fetch origin $(echo "${{branch}}" | cut -f2- -d/)
+
+            if [ -n "${{commit}}" ]
+            then
+                BASE=${{commit}}
+            else
+                BASE=FETCH_HEAD
+            fi
+            # Attempt rebasing it on top of upstream master
+            if ! git rebase ${{BASE}}
+            then
+                # If this fails, clean up...
+                git rebase --abort
+                # and exit with an error
+                exit 1
+            fi
+
+            COMMIT_TO_PUSH="HEAD"
+            TAGNAME="d${{BUILD_ID}}_rebase"
+          elif [ "${{branch}}" = "unknown" -a "${{GIT_COMMIT}}" != "${{GIT_PREVIOUS_COMMIT}}" ] || [ "${{branch}}" = "jiocloud/devmaster" ]
+          then
+            # Jenkins should have already made sure that it's checked out
+            # so we don't need to do anything here.
+            TAGNAME="d${{BUILD_ID}}_forced"
+            COMMIT_TO_PUSH="${{GIT_COMMIT}}"
+          elif [ "${{branch}}" = "unknown" ]
+          then
+              echo "No branch set and no changes detected. Erring on the side of caution and bailing out."
+              exit 0
+          else
+            echo "Not sure what to do with branch ${{branch}}"
+            exit 1
+          fi
+
+          # If that works out, tag it and push to github
+          git tag "${{TAGNAME}}"
+          git push jiocloud +${{COMMIT_TO_PUSH}}:master "${{TAGNAME}}"
+
+          # Run the tests.
+          if ! tox -e py27
+          then
+              exit 1
+          fi
+      - trigger-builds:
+          - project: "{name}-pkg"
+
+    properties:
+      - github:
+          url: https://github.com/JioCloud/{name}/
+
+    publishers:
+      - ircbot:
+          strategy: failure-and-fixed
+          matrix-notifier: only-configurations
+
+    wrappers:
+      - ssh-agent:
+          credentials-id: 46c0cb26-2b11-443c-b556-0f7631f02410
 
 - job-group:
     name: upstream-project-nostable
@@ -148,6 +264,13 @@
     jobs:
       - "{name}-upstream"
       - "{name}-jiocloud"
+
+- job-group:
+    name: upstream-project-nostable-rebase-fix-testing
+    srcbranch: master
+    jobs:
+      - "{name}-upstream"
+      - "{name}-jiocloud-rebase-fix-testing"
 
 - job-group:
     name: upstream-project
@@ -210,7 +333,7 @@
     pkgbranch: jiocloud/master
     codebranch: jiocloud/master
     jobs:
-      - upstream-project-nostable
+      - upstream-project-nostable-rebase-fix-testing
       - '{name}-pkg'
 
 - project:
