Update branch handling based on discussion with Rushi

diff --git a/jobs.yaml b/jobs.yaml
--- a/jobs.yaml
+++ b/jobs.yaml
@@ -140,11 +140,6 @@
           name: jiocloud
           merge:
             branch: jiocloud/devmaster
-      - git:
-          url: git@github.com:JioCloud/cinder.git
-          name: jiocloud
-          merge:
-            branch: jiocloud/manualmaster
 
     triggers:
       - pollscm: "H/15 * * * *"
@@ -154,45 +149,39 @@
           #!/bin/bash
           if [ "$GIT_BRANCH" = "origin/master" ]
           then
-            # Push rebased changes to jiocloud/master, and merged 
-            # changes to jiocloud/devmaster
-          
-            git checkout -b jiocloud_master jiocloud/master;
-            git rebase origin/master;
-            tox -e py27;
-            git push jiocloud jiocloud_master:master --force;
-          
-            # If rebase succeeds, then merge too will!
-            # NOTE!: merge may not, as jiocloud/devmaster might have 
-            # changed, but that is user's fault!
-            git checkout -b jiocloud_devmaster jiocloud/devmaster;
-            git branch -D jiocloud_master;
-            git merge origin/master;
-            git push jiocloud jiocloud_devmaster:devmaster;
-          
-            git checkout master;
-            git branch -D jiocloud_devmaster;
-            git remote update jiocloud;
-          elif [ "$GIT_BRANCH" = "jiocloud/manualmaster" ]
-          then
-            git checkout -b jiocloud_manualmaster;
-            tox -e py27;
-            git push jiocloud jiocloud_manualmaster:master --force;
-            git checkout master;
-            git branch -D jiocloud_manualmaster;
+            # First make sure we have a local branch to work with
+            if ! git checkout jiocloud_master
+            then
+                git checkout -b jiocloud_master jiocloud/master
+            fi
+            # ...then make sure it's up-to-date.
+            git pull jiocloud master
+
+            # Attempt rebasing it on top of upstream master
+            if ! git rebase origin/master
+            then
+                # If this fails, clean up...
+                git rebase --abort
+                # and exit with an error
+                exit 1
+            fi
+
+            TAGNAME="rebase_${BUILD_ID}"
           elif [ "$GIT_BRANCH" = "jiocloud/devmaster" ]
-          then
-            git checkout -b jiocloud_devmaster jiocloud/devmaster;
-            git rebase jiocloud/master;
-            tox -e py27;
-            git push jiocloud jiocloud_devmaster:master --force;
-            git checkout master;
-            git branch -D jiocloud_devmaster;
-          elif [ "$GIT_BRANCH" = "jiocloud/master" ]
-          then
-            echo "Not building jiocloud/master branch. Skipping";
+            # Jenkins should have already made sure that it's checked
+            # so we don't need to do anything here.
+            TAGNAME="forced_${BUILD_ID}"
           else
-            exit 1;
+            echo "Not sure what to do with branch $GIT_BRANCH"
+            exit 1
+          fi
+
+          # Run the tests.
+          if tox -e py27
+          then
+              # If that works out, tag it and push to github
+              git tag "${TAGNAME}"
+              git push jiocloud +HEAD:master "${TAGNAME}"
           fi
 
     properties:
