Add PROJECT-pkg job template and enable it for Nova

diff --git a/jobs.yaml b/jobs.yaml
--- a/jobs.yaml
+++ b/jobs.yaml
@@ -157,8 +157,10 @@
 - project:
     name: nova
     organization: openstack
+    codebranch: jiocloud/master
     jobs:
       - upstream-project
+      - '{name}-pkg'
 
 - project:
     name: python-novaclient
@@ -245,6 +247,103 @@
     organization: sorenh
     jobs:
       - upstream-project-nostable
+
+- job-template:
+    name: "{name}-pkg"
+    project-style: freestyle
+    node: cloud
+    logrotate:
+      daysToKeep: 10
+      numToKeep: 20
+      artifactDaysToKeep: 7
+      artifactNumToKeep: 15
+    scm:
+      - git:
+          url: git@github.com:JioCloud/{name}.git
+          name: jiocloud
+          branches:
+            - "{codebranch}"
+            - jiocloud/packaging
+          basedir: build
+          credentials-id: 46c0cb26-2b11-443c-b556-0f7631f02410
+
+    triggers:
+      - pollscm: "H/15 * * * *"
+
+    builders:
+      - shell: |
+          #!/bin/bash -xe
+          rm -f ./* || true
+
+          cd build
+
+          # We could have been triggered either by a change on the pkg
+          # branch or master. First, we need master.
+          if ! git checkout master
+          then
+              git branch -t master {codebranch}
+              git checkout master
+          fi
+          git pull
+
+          # This gives us something like 2014.1.2.dev3.f72b5de
+          upstream_version=$(python setup.py --version)
+          upstream_name=$(python setup.py --name)
+
+          python setup.py sdist
+          mv dist/*.tar.gz ../${{upstream_name}}_${{upstream_version}}.orig.tar.gz
+
+          # Clean up
+          git clean -dfx
+
+          # Now grab packaging
+          if ! git checkout packaging
+          then
+              git checkout -b packaging jiocloud/packaging
+          fi
+
+          # and rebase it on the code branch
+          git rebase {codebranch}
+
+          # Keep the current epoch
+          current_epoch=$(dpkg-parsechangelog  | grep ^Version: | cut -f2 -d' ' | grep -o ^.*:)
+
+          # Someone needs to tak the blame
+          export DEBEMAIL=Soren.Hansen@ril.com
+          export DEBFULLNAME="JioCloud Jenkins"
+
+          # Create a changelog entry
+          dch -D precise -v ${{current_epoch}}${{upstream_version}}-jiocloud1 'Automatic build'
+
+          # and build the source package
+          dpkg-buildpackage -S -nc --source-option=--auto-commit
+          cd ..
+          sbuild -n -d precise -A *.dsc
+      - trigger-builds:
+          - project: "process-pkg"
+            predefined-parameters: |
+              triggering_job=${{JOB_NAME}}
+              triggering_build_number=${{BUILD_NUMBER}}
+
+
+    properties:
+      - copyartifact:
+          projects: process-pkg
+      - github:
+          url: https://github.com/JioCloud/{name}/
+
+    publishers:
+      - ircbot:
+          strategy: failure-and-fixed
+          matrix-notifier: only-configurations
+      - archive:
+          artifacts: '*.dsc,*.diff.gz,*.tar.gz,*.changes,*.deb'
+          allow-empty: 'true'
+
+    wrappers:
+      - ssh-agent:
+          credentials-id: 46c0cb26-2b11-443c-b556-0f7631f02410
+
 
 - job-template:
     name: "{name}-pkg-temp"
